name: stagexl_richtextfield
version: 0.3.2
authors:
- Alex Gann <k.alexgann@gmail.com>
- Bernhard Pichler <support@stagexl.org>
author:
description: StageXL Extension for RichTextField support.
homepage: https://github.com/bp74/StageXL_RichTextField
documentation: https://github.com/bp74/StageXL_RichTextField

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  stagexl: '>=1.4.6 <2.0.0'

dev_dependencies:
  pedantic: any
  build_test: any
  build_runner: any
  build_web_compilers: any
